import { Category } from "@/features/catalog/types";

// Frontend-owned taxonomy. The backend still resolves the slug to its persisted UUID on save.
export const PRODUCT_CATEGORIES: Category[] = [
  { id: "rice-grains", name: "Rice & Grains", slug: "rice-grains", description: "Rice, wheat, millets, oats and other grains" },
  { id: "pulses-lentils", name: "Pulses & Lentils", slug: "pulses-lentils", description: "Dal, rajma, chana, peas and lentils" },
  { id: "flour-atta", name: "Flour & Atta", slug: "flour-atta", description: "Atta, maida, besan and baking flour" },
  { id: "edible-oils", name: "Edible Oils", slug: "edible-oils", description: "Cooking oils, ghee and vanaspati" },
  { id: "spices-masala", name: "Spices & Masala", slug: "spices-masala", description: "Whole spices, powders and masala blends" },
  { id: "sugar-salt", name: "Sugar & Salt", slug: "sugar-salt", description: "Sugar, salt, jaggery and sweeteners" },
  { id: "packaged-foods", name: "Packaged Foods", slug: "packaged-foods", description: "Ready-to-cook, canned and packaged foods" },
  { id: "biscuits-cookies", name: "Biscuits & Cookies", slug: "biscuits-cookies", description: "Biscuits, cookies and rusks" },
  { id: "chips-namkeen", name: "Chips & Namkeen", slug: "chips-namkeen", description: "Chips, namkeen and savoury snacks" },
  { id: "tea-coffee", name: "Tea & Coffee", slug: "tea-coffee", description: "Tea, coffee, premixes and hot beverages" },
  { id: "soft-drinks-juices", name: "Soft Drinks & Juices", slug: "soft-drinks-juices", description: "Cold drinks, juices, water and energy drinks" },
  { id: "milk-curd", name: "Milk & Curd", slug: "milk-curd", description: "Milk, curd and dairy beverages" },
  { id: "butter-cheese", name: "Butter & Cheese", slug: "butter-cheese", description: "Butter, cheese, paneer and spreads" },
  { id: "bread-bakery", name: "Bread & Bakery", slug: "bread-bakery", description: "Bread, buns, cakes and bakery products" },
  { id: "eggs", name: "Eggs", slug: "eggs", description: "Eggs and egg-based products" },
  { id: "fresh-fruits", name: "Fresh Fruits", slug: "fresh-fruits", description: "Fresh seasonal fruits" },
  { id: "fresh-vegetables", name: "Fresh Vegetables", slug: "fresh-vegetables", description: "Fresh vegetables and leafy greens" },
  { id: "meat-seafood", name: "Meat & Seafood", slug: "meat-seafood", description: "Meat, chicken, fish and seafood" },
  { id: "soap-bath", name: "Soap & Bath", slug: "soap-bath", description: "Bath soaps, body wash and bath essentials" },
  { id: "hair-care", name: "Hair Care", slug: "hair-care", description: "Shampoo, conditioner, oil and hair styling" },
  { id: "skin-care", name: "Skin Care", slug: "skin-care", description: "Creams, lotions, face care and sunscreen" },
  { id: "oral-care", name: "Oral Care", slug: "oral-care", description: "Toothpaste, brushes and mouth care" },
  { id: "baby-care", name: "Baby Care", slug: "baby-care", description: "Diapers, baby food and baby essentials" },
  { id: "laundry-care", name: "Laundry Care", slug: "laundry-care", description: "Detergent, fabric care and stain removers" },
  { id: "home-cleaning", name: "Home Cleaning", slug: "home-cleaning", description: "Floor, toilet, dish and surface cleaners" },
  { id: "kitchen-supplies", name: "Kitchen Supplies", slug: "kitchen-supplies", description: "Kitchen tools, containers and consumables" },
  { id: "puja-religious", name: "Puja & Religious", slug: "puja-religious", description: "Puja items, incense and religious essentials" },
  { id: "stationery-office", name: "Stationery & Office", slug: "stationery-office", description: "Pens, paper, notebooks and office supplies" },
  { id: "books-magazines", name: "Books & Magazines", slug: "books-magazines", description: "Books, newspapers and magazines" },
  { id: "toys-games", name: "Toys & Games", slug: "toys-games", description: "Toys, games and children entertainment" },
  { id: "mens-clothing", name: "Mens Clothing", slug: "mens-clothing", description: "Mens clothing and daily wear" },
  { id: "womens-clothing", name: "Womens Clothing", slug: "womens-clothing", description: "Womens clothing and daily wear" },
  { id: "kids-clothing", name: "Kids Clothing", slug: "kids-clothing", description: "Kids clothing and school wear" },
  { id: "footwear", name: "Footwear", slug: "footwear", description: "Shoes, sandals and slippers" },
  { id: "mobile-accessories", name: "Mobile Accessories", slug: "mobile-accessories", description: "Chargers, cables, cases and earphones" },
  { id: "electronics", name: "Electronics", slug: "electronics", description: "Small appliances and consumer electronics" },
  { id: "hardware-electrical", name: "Hardware & Electrical", slug: "hardware-electrical", description: "Tools, bulbs, wires and electrical supplies" },
  { id: "pharmacy", name: "Pharmacy", slug: "pharmacy", description: "Daily medicines and first-aid products" },
  { id: "vitamins-supplements", name: "Vitamins & Supplements", slug: "vitamins-supplements", description: "Vitamins, nutrition and wellness products" },
  { id: "pet-supplies", name: "Pet Supplies", slug: "pet-supplies", description: "Pet food, hygiene and accessories" },
  { id: "automotive", name: "Automotive", slug: "automotive", description: "Vehicle care, accessories and essentials" },
  { id: "sports-fitness", name: "Sports & Fitness", slug: "sports-fitness", description: "Sports goods and fitness accessories" },
  { id: "gifts-handicrafts", name: "Gifts & Handicrafts", slug: "gifts-handicrafts", description: "Gifts, decor and handmade products" },
];