/**
 * Exact routes mapped from C:\Go\shopMe\internal\handler\routes\router.go
 */
export const Endpoints = {
  HEALTH: "/health",
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    GOOGLE: "/auth/google",
    FORGOT_PASSWORD: "/auth/forgot-password",
    RESET_PASSWORD: "/auth/reset-password",
    REFRESH: "/auth/refresh",
  },
  USER: {
    ME: "/user/me",
    PROFILE: "/user/profile",
    AVATAR: "/user/avatar",
    LOYALTY: "/user/loyalty",
  },
  CATALOG: {
    HOME_FEED: "/catalog/home-feed",
  },
  CATEGORIES: {
    LIST: "/categories",
  },
  PRODUCTS: {
    LIST: "/products",
    NEARBY: "/products/nearby",
    DETAIL: (id: string) => `/products/${id}`,
    BY_SLUG: (slug: string) => `/products/slug/${slug}`,
    SCAN: (code: string) => `/products/scan/${code}`,
    UPLOAD_IMAGES: "/products/images",
    SUGGEST_MEDIA: "/products/media/suggest",
    BULK_IMPORT: "/shops/me/products/bulk-import",
    IMPORT_TEMPLATE: "/shops/me/products/import-template.csv",
  },
  SHOPS: {
    LIST: "/shops",
    DETAIL: (id: string) => `/shops/${id}`,
    BY_SLUG: (slug: string) => `/shops/slug/${slug}`,
    PRODUCTS: (slug: string) => `/shops/${slug}/products`,
    REVIEWS: (slug: string) => `/shops/${slug}/reviews`,
    OFFERS: (slug: string) => `/shops/${slug}/offers`,
  },
  MERCHANT: {
    MY_SHOP: "/shops/me",
    MY_PRODUCTS: "/shops/me/products",
    DASHBOARD: "/shops/me/dashboard",
    STATUS: "/shops/me/status",
    DIGEST: "/shops/me/digest",
    UPLOAD_IMAGES: "/shops/me/images",
    POS_SALE: "/shops/me/pos/sale",
    POS_SUMMARY: "/shops/me/pos/daily-summary",
    PARSE_PARCHI: "/shops/me/pos/parse-parchi",
    KHATA: "/shops/me/khata",
    KHATA_AGING: "/shops/me/khata/aging",
    KHATA_PAYMENT: (mobile: string) => `/shops/me/khata/${mobile}/payment`,
    KHATA_STATEMENT: (mobile: string) => `/shops/me/khata/${mobile}/statement`,
    KHATA_STATEMENT_PDF: (mobile: string) => `/shops/me/khata/${mobile}/statement.pdf`,
    KHATA_REQUEST_CLOSURE: (id: string) => `/shops/me/khata/${id}/request-closure`,
    KHATA_VERIFY_CLOSURE: (id: string) => `/shops/me/khata/${id}/verify-closure-otp`,
    KHATA_REVERSE_TX: (id: string, txId: string) => `/shops/me/khata/${id}/transactions/${txId}/reverse`,
    KHATA_RESOLVE_DISPUTE: (id: string, txId: string) => `/shops/me/khata/${id}/dispute/${txId}/resolve`,
    KHATA_PROMISE_DATE: (id: string) => `/shops/me/khata/${id}/promise-date`,
    KHATA_TRUST_SCORE: (mobile: string) => `/shops/me/khata/${mobile}/trust-score`,
    KHATA_CREDIT_LIMIT: (mobile: string) => `/shops/me/khata/${mobile}/credit-limit`,
    LOW_STOCK: "/shops/me/inventory/low-stock",
    ADJUST_STOCK: "/shops/me/inventory/adjust",
    REORDER_SHEET: "/shops/me/inventory/reorder-sheet.pdf",
    DEMAND_WATCHLIST: "/shops/me/inventory/demand-watchlist",
    EXPENSES: "/shops/me/expenses",
    PROFIT: "/shops/me/analytics/profit",
    PRODUCT_MATRIX: "/shops/me/analytics/products",
    DAILY_SUMMARY: "/shops/me/pos/daily-summary",
    WEEKLY_SCORECARD: "/shops/me/pos/weekly-scorecard",
    CREATE_OFFER: "/shops/me/offers",
    UPDATE_OFFER: (id: string) => `/shops/me/offers/${id}`,
    DELETE_OFFER: (id: string) => `/shops/me/offers/${id}`,
    OFFERS_HISTORY: "/shops/me/offers/history",
    RESERVATIONS: "/shops/me/reservations",
    VERIFY_PICKUP: "/shops/me/reservations/verify",
    COPILOT: "/ai/merchant-copilot",
    STAFF: {
      LIST: "/shops/me/staff",
      CREATE: "/shops/me/staff",
      UPDATE: (id: string) => `/shops/me/staff/${id}`,
      DELETE: (id: string) => `/shops/me/staff/${id}`,
      LOGIN: "/auth/staff-login",
    },
  },
  AI: {
    CUSTOMER_CHAT: "/ai/customer-chat",
    MERCHANT_COPILOT: "/ai/merchant-copilot",
    SCAN_PRODUCT: "/ai/scan-product",
    PARSE_PARCHI: "/ai/parse-parchi",
    SEMANTIC_SEARCH: "/ai/semantic-search",
    VOICE_BILL: "/ai/voice-bill",
    MARKETING_CAMPAIGN: "/ai/marketing-campaign",
    BARGAIN_ASSIST: "/ai/bargain-assist",
  },
  CUSTOMER_KHATA: {
    SUMMARY: "/customer/khata",
    PASSBOOK: (khataId: string) => `/customer/khata/${khataId}/transactions`,
    DISPUTE: (khataId: string) => `/customer/khata/${khataId}/dispute`,
    PAY_UPI: (khataId: string) => `/customer/khata/${khataId}/pay-upi`,
    STATEMENT_PDF: (khataId: string) => `/customer/khata/${khataId}/statement.pdf`,
    REQUEST_CLOSURE: (khataId: string) => `/customer/khata/${khataId}/request-closure`,
    VERIFY_CLOSURE: (khataId: string) => `/customer/khata/${khataId}/verify-closure-otp`,
    SET_OTP_PROTECTION: (khataId: string) => `/customer/khata/${khataId}/otp-protection`,
    PROMISE_DATE: (khataId: string) => `/customer/khata/${khataId}/promise-date`,
  },
  RESERVATIONS: {
    CREATE: "/reservations",
    USER_LIST: "/reservations",
    DETAIL: (id: string) => `/reservations/${id}`,
    CANCEL: (id: string) => `/reservations/${id}/cancel`,
  },
  OFFERS: {
    LIST: "/offers",
  },
  REPORTS: "/reports",
} as const;
